version: "3.8"
services:
    phpserver:
        container_name: phpserver-${APP_NAME}
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:8080
        depends_on:
            database:
                condition: service_started
            redis:
                condition: service_started
    database:
        container_name: ${DB_HOST}
        image: mariadb
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        restart: always
        volumes:
            - db-data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        depends_on:
            - database
        ports:
            - 8080:8080
    redis:
        container_name:  redis-${APP_NAME}
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379
volumes:
    db-data: ~
